services:

  api_b:
    container_name: api_b
    build: .
    volumes:
      - .:/code/
    env_file:
      - .env_api_b
    ports:
      - "8002:8002"
    networks:
      - my-proxy-net
    command: uvicorn main:app --host 0.0.0.0 --port 8002

networks:
  my-proxy-net:
    external:
      name: custom_network
